import Head from '../node_modules/next/head'
import styles from '../styles/Home.module.css'
import Board from '../components/Board'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tic Tac Toe Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Board />

      </main>
    </div>
  )
}
